name: flame_gdx_texture_packer
description: "This package is no longer maintained. Please use the official package flame_texturepacker maintained by the Flame team. You can find it here: https://pub.dev/packages/flame_texturepacker."
version: 0.6.2
repository: https://github.com/Yayo-Arellano/flame_texture_packer
issue_tracker: https://github.com/Yayo-Arellano/flame_texture_packer/issues
tags:
  - discontinued

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter: